name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ba57417ab332f1ec4eb8bd38ff273b2352f276ea56bc141fd22f19e9b93806b"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
