name = "Sky FABRICation 3"
author = "MSandro"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "577dd09df6e90e80533c1c7f7e3dbffc37f43ce15988e0318049430e5ef43874"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
