name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9435d3cc276a3bbc0831bcd74fdab5c6c7807002768816811c3e8c928b3689e"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
