name = "Sky FABRICation 3"
author = "MSandro"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c7f3fe901bdcf5de0780ca334f4d9b2318ee80074930a74bdbfe4d8a0a4375"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
