name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4969d6d95151d2e006797ccb0bc4f6fc8780cc4b37cc197688fa93910a982e43"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
