name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9b75fbb90abb7a5447a63364c1d6b6196505b699b3866b4fce0b955687ec72b"

[versions]
fabric = "0.14.18"
minecraft = "1.18.2"
