name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8734b75b466e3c36d04f3306c750020607d4cf428a60ede5324e4ea82cb0f03"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
