name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ac137d8091d366448bc92f394dc55c1c797ce9e604140b95da7a7159df6abb8"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
