name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5b440dea5f2769db0ff7c32a4975c8ad3ec7a6d3ce8e330c6b9f30f06e5e84"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
