name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b3fcd8c742fa126845ec52ebed7b94d795ef9c0e85f43f7c07b88baac64dec"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
