name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f03ad9a3b24300ba1656724e8f061af45f72e4c8ae8f8f389ae394a258be0eac"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
