name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b2b0541c796cb93824b425f5990d20c2d08ca96f8159068107f5bbdfee509a4"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
