name = "Sky FABRICation 3"
author = "MSandro"
version = "0.5.6a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f383082ff43f3b040e021cc18ca96b4e6aa5a6131e16c3d7c99166dd895920b0"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
