name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae9943654aa3b2c78d3beccbf16e4b67096556c013979b44d19ea4ca613a3f3"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
